### ISSUE TITLE
上传成功后怎么获取服务器返回的数据？

### ISSUE THREAD

**Issue by MrYinGJ** [lishuhao/sy_flutter_qiniu_storage#15]
图片上传成功后，我们自己的服务器会返回数据给七牛云服务器，然后客户端怎么从七牛云接收这个回调呢？

**Comment by peak77** [comment]
最后拿到了吗

**Comment by MrYinGJ** [comment]
我们最后的解决方案是在flutter中使用网页端的上传接口来上传图片，没有使用这个库

**Comment by lishuhao** [comment]
新版本返回了更详细的信息 @MrYinGJ @peakerWu
