### ISSUE TITLE
打包报错了 

### ISSUE THREAD

**Issue by gwsh** [lishuhao/sy_flutter_qiniu_storage#16]
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':sy_flutter_qiniu_storage:verifyReleaseResources'.                                      
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade                  
   > Android resource linking failed                                                                               
     /Users/gwsh/work-utils/repository/caches/transforms-2/files-2.1/7faf2ad74a0b9932e38d86e684646e95/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                                                                   
     /Users/gwsh/work-utils/repository/caches/transforms-2/files-2.1/7faf2ad74a0b9932e38d86e684646e95/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

**Comment by gwsh** [comment]
已解决 版本 Android 切换成 28

**Comment by houkhan** [comment]
我也遇到了这个问题  在flutter1.15.0上  在切换到Android28问题并没有解决

**Comment by houkhan** [comment]
我想请教一下您的flutter版本是多少呢 会不会是flutter版本的问题

**Comment by houkhan** [comment]
然而我尝试更新到目前最新的flutter版本还是有这个问题，我的安卓版本也是28的

**Comment by gwsh** [comment]
> 然而我尝试更新到目前最新的flutter版本还是有这个问题，我的安卓版本也是28的

不是你当前项目的Android 是插件的Android工程

**Comment by houkhan** [comment]
OK  谢谢  已解决
