### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by hwh97** [lishuhao/sy_flutter_qiniu_storage#2]
///上传
  ///
  /// key 保存到七牛的文件名
  upload(String filepath, String token, String key) async {
    var res = await _channel.invokeMethod('upload',
        <String, String>{"filepath": filepath, "token": token, "key": key});
    print(res);
  }
这里是不是缺少了return res ？

**Comment by yiqun** [comment]
根本就没有 return res，这样的插件怎么就发布了？

**Comment by lishuhao** [comment]
0.1.4版本upload添加返回值
